server:
  port: ${PORT:9052}

spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}

spring:
  codec:
    max-in-memory-size: 5MB
  jmx:
    enabled: true
  data:
    mongodb:
      no_cursor_timeout: true
      auto-index-creation: true
      uri: ${MONGO_URI:mongodb://localhost:27017/masterData}
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB

fileuploadpath: /tmp/

logging.level.org.springframework.cache: TRACE

aws:
  bucket:
    name: ${MASTER_SERVICE_V2_AWS_S3_BUCKET:docs.turtle-feature.com}
